#!/bin/bash

if [ -e $__object/parameter/version ]; then
    version=$( cat $__object/parameter/version )
else
    version="2.4.3"
fi

installed_version=$(cat $__object/explorer/exists)

if [ ${installed_version} = ${version} ]; then
    exit 0;
fi

cat <<EOF
chmod +x /tmp/build_opencv.sh
/tmp/build_opencv.sh ${version}
rm /tmp/build_opencv.sh
EOF
