#!/bin/bash

# Also needs nvidia-cuda-toolkit >=4.1, there is no
# good automated way to install this yet.

packages="
cmake
libjpeg-dev
libpng12-dev
libtiff4-dev
libjasper-dev
libopenexr-dev
libgtk2.0-dev
libdc1394-22-dev
libavbin-dev
libswscale-dev
libavformat-dev
libtbb-dev
libgstreamer-plugins-base0.10-dev
libv4l-dev
python-sphinx
"

for pkg in $packages
do
    __package $pkg --state present
done

__nvidia_cuda --state present \
    --download \
    --force_ubuntu_release=11.10 \
    --update=1 \
    --version=5.0.35

if [ -e $__object/parameter/version ]; then
    version=$( cat $__object/parameter/version )
else
    version="2.4.3"
fi

installed_version=$(cat $__object/explorer/exists)

if [ ${installed_version} = ${version} ]; then
    exit 0;
fi

__file /tmp/build_opencv.sh --state present \
    --source "$__type/files/build_opencv.sh"
export version
mkdir -p $__object/files
"$__type/templates/opencv.pc.sh" > "$__object/files/opencv.pc"
__directory /usr/local/lib/pkgconfig --state present
require="__directory/usr/local/lib/pkgconfig" \
    __file /usr/local/lib/pkgconfig/opencv.pc --state present \
    --source "$__type/files/opencv.pc"
