#!/bin/bash

packages="
wget
build-essential
cmake
unzip
libqt4-dev
libjpeg-dev
libpng12-dev
libtiff4-dev
libjasper-dev
libopenexr-dev
libgtk2.0-dev
libdc1394-22-dev
libavbin-dev
libswscale-dev
libavformat-dev
libtbb-dev
libgstreamer-plugins-base0.10-dev
libv4l-dev
python-sphinx
nvidia-cuda-toolkit
nvidia-cuda-dev
"
for pkg in $packages
do
    __package $pkg --state present
done

if [ -e $__object/parameter/version ]; then
    version=$( cat $__object/parameter/version )
else
    version="2.4.3"
fi

installed_version=$(cat $__object/explorer/exists)

if [ ${installed_version} = ${version} ]; then
    exit 0;
fi

__file /tmp/build_opencv.sh --state present \
    --source "$__type/files/build_opencv.sh" \
    --mode 0744
export version
mkdir -p $__object/files
"$__type/templates/opencv.pc.sh" > "$__object/files/opencv.pc"
__directory /usr/local/lib/pkgconfig --state present
require="__directory/usr/local/lib/pkgconfig" \
    __file /usr/local/lib/pkgconfig/opencv.pc --state present \
    --source "$__type/files/opencv.pc" \
    --mode 0644
