#!/bin/sh

while read host; do
    set $host
    __line ${2}_entry --file /etc/hosts --line "${host}" </dev/null
    case ${2} in
        ${__target_host}-wireless*)
            WIRELESS_IP=$1
            ;;
        ${__target_host})
            WIRED_IP=$1
            ;;
    esac
done < "$__type/files/hosts"
export WIRED_IP WIRELESS_IP

export WIRED_INTERFACE="eth0"
export WIRED_NM="255.255.0.0"
export WIRED_GW="10.10.1.1"
export WIRED_NS="10.10.10.10"
export WIRELESS_CHANNEL="4"
export WIRELESS_SSID="survey"
export WIRELESS_KEY="752ac5142d"
export WIRELESS_NM="255.255.255.0"
if [ "$(cat $__object/explorer/${WIRED_INTERFACE}_address)" = "${WIRED_IP}" -a \
	 "$(cat $__object/explorer/${WIRED_INTERFACE}_gateway)" = "${WIRED_GW}" -a \
	 "$(cat $__object/explorer/${WIRED_INTERFACE}_netmask)" = "${WIRED_NM}" -a \
	 "$(cat $__object/explorer/${WIRED_INTERFACE}_nameserver)" = "${WIRED_NS}" -a \
	 "$(cat $__object/explorer/wlan0_address)" = "${WIRELESS_IP}" -a \
	 "$(cat $__object/explorer/wlan0_netmask)" = "${WIRELESS_NM}" -a \
	 "$(cat $__object/explorer/wlan0_wireless-channel)" = "${WIRELESS_CHANNEL}" -a \
	 "$(cat $__object/explorer/wlan0_wireless-essid)" = "${WIRELESS_SSID}" -a \
	 "$(cat $__object/explorer/wlan0_wireless-key)" = "${WIRELESS_KEY}" ] ; then
# all set, don't change a thing
true
else
	# create new file
	mkdir -p "$__object/files"
	"$__type/templates/interfaces.sh" > "$__object/files/interfaces"
	__file /etc/network/interfaces --source "$__object/files/interfaces"
fi

if [ -n "${WIRELESS_IP}" ]; then
    __file /etc/udev/rules.d/80-hotplug-wlan.rules \
        --source $__manifest/files/80-hotplug-wlan.rules
fi

__file /etc/ethers --source "$__type/files/ethers"


