#!/bin/bash
if [ -f "$__object/parameter/repository" ]; then
   name="$(cat "$__object/parameter/repository")"
else
   name="$__object_id"
fi

if [ -f "$__object/parameter/keyurl" ]; then
   keyurl="$(cat "$__object/parameter/keyurl")"
else
   keyurl=""
fi

state_should="$(cat "$__object/parameter/state")"
state_is="$(cat "$__object/explorer/repository")"

[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
    present)
        echo "apt-add-repository \"$name\""
        if [ "$keyurl" != "" ]; then
            echo "wget "$keyurl" -O - | apt-key add -"
        fi
    ;;
    absent)
        echo "apt-add-repository --remove \"$name\""
    ;;
    *)
        echo "Unknown state: $state_should" >$2
        exit 1
    ;;
esac
