#!/bin/bash
# Every machine becomes a marker, so sysadmins know that automatic
# configurations are happening
__file /etc/cdist-configured

case "$__target_host" in
    blue18*)
        export ETH0_IP="10.10.180.20"
        export WLAN_IP="192.168.200.20"
        . $__manifest/samplereturn
        ;;
    moline*)
        export ETH0_IP="10.10.180.21"
        export WLAN_IP="192.168.200.21"
        . $__manifest/samplereturn
        ;;

esac
