#!/bin/bash

__workstation

__package wakeonlan --state present

__user --home /home/robot \
       --groups "adm,dialout,cdrom,plugdev,lpadmin,admin,sambashare,video" \
       --shell /bin/bash \
       robot
require="__user/robot" \
    __directory /home/robot \
    --owner robot \
    --group robot \
    --mode 755

require="__directory/home/robot" \
    __ssh_authorized_key \
    --srcfile $__manifest/files/robot_rsa.pub \
    --dstuser robot \
    robot
require="__ssh_authorized_key/robot" \
    __file /home/robot/.ssh/robot_rsa \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa
require="__ssh_authorized_key/robot" \
    __file /home/robot/.ssh/robot_rsa.pub \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa.pub

require="__user/robot" \
    __addifnosuchline autologin_user \
    --file /etc/lightdm/lightdm.conf \
    --line 'autologin-user=robot'
require="__user/robot" \
    __addifnosuchline autologin_timeout \
    --file /etc/lightdm/lightdm.conf \
    --line 'autologin-user-timeout=0'

require="__user/robot" \
    __directory /home/robot/.config \
    --owner robot \
    --group robot
require="__directory/home/robot/.config" \
    __directory /home/robot/.config/autostart \
    --owner robot \
    --group robot
require="__directory/home/robot/.config/autostart" \
    __file /home/robot/.config/autostart/roscore.desktop \
    --source $__manifest/files/roscore.desktop \
    --owner robot \
    --group robot \
    --mode 777

require="__user/robot" \
    __gsettings aclidaction \
    --user robot \
    --schema org.gnome.settings-daemon.plugins.power \
    --key lid-close-ac-action \
    --value nothing
require="__user/robot" \
    __gsettings battlidaction \
    --user robot \
    --schema org.gnome.settings-daemon.plugins.power \
    --key lid-close-battery-action \
    --value nothing
require="__user/robot" \
    __gsettings noautomount \
    --user robot \
    --schema org.gnome.desktop.media-handling \
    --key automount \
    --value false
require="__user/robot" \
    __dotfiles robot

__addifnosuchline modules_acpiphp \
    --line "acpiphp" \
    --file "/etc/modules"

__kvaser_canlib --tarname "linuxcan" --version "4.78-3" --devices "leaf"

__package_apt libtbb-dev --state present
__package_apt libsuitesparse-dev --state present

__ros
require="__ros" __package_apt ros-electric-joystick-drivers --state present
require="__ros" __package_apt ros-electric-camera-drivers --state present 
require="__ros" __package_apt ros-electric-dynamixel-motor --state present 
require="__ros" __package_apt ros-electric-bosch-drivers --state present 

__opencv

__ros_opencv_overlay
__addifnosuchline rossetup \
    --line ". /opt/ros/opencv_overlay/overlay_setup.sh" \
    --file "/etc/bash.bashrc"

__samplereturn_network --ETH0_IP=$ETH0_IP --WLAN_IP=$WLAN_IP
