#!/bin/bash

__apt_ppa "ppa:mozillateam/firefox-next" --state enabled
__apt_ppa "ppa:mozillateam/thunderbird-next" --state enabled

require="__apt_ppa/ppa:mozillateam/firefox-next __apt_ppa/ppa:mozillateam/thunderbird-next"\
    __apt_upgrade

packages="
vim
ctags
vim-doc
vim-scripts
git-all
subversion
cvs
terminator
build-essential
manpages-dev
manpages-posix-dev
manpages-posix
texlive
screen
byobu
tmux
smbfs
python-dev
gfortran
python-numpy
python-scipy
python-matplotlib
ipython
python-pip
python-wxtools
cython
swig
sshfs
htop
apt-file
acpi
cmake
vlc
x11vnc
graphicsmagick-imagemagick-compat
gkrellm
pidgin
pidgin-otr
pidgin-encryption
pidgin-latex
virtualbox
pulseaudio-module-zeroconf
paman
paprefs
pavucontrol
bwm-ng
gscanbus
network-manager-vpnc
"

for pkg in $packages
do
    __package $pkg --state present
done


