#!/bin/sh

cat <<EOF
# Auto-generated by cdist __samplereturn_network
# Please edit template
auto lo
iface lo inet loopback

auto ${WIRED_INTERFACE}
iface ${WIRED_INTERFACE} inet static
 address ${WIRED_IP}
 netmask ${WIRED_NM}
EOF
if [ -n "${WIRED_GW}" ]; then
    echo "gateway ${WIRED_GW}"
fi
cat <<EOF
auto wlan0
iface wlan0 inet static
  wireless-mode ad-hoc
  wireless-channel ${WIRELESS_CHANNEL}
  wireless-essid ${WIRELESS_SSID}
  wireless-key ${WIRELESS_KEY}
  address ${WIRELESS_IP}
  netmask ${WIRELESS_NM}
EOF
