#!/bin/sh

cat <<EOF
# Auto-generated by cdist __samplereturn_network
# Please edit template
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
 address ${ETH0_IP}
 netmask ${ETH0_NM}
 gateway ${ETH0_GW}

auto wlan0
iface wlan0 inet static
  wireless-mode ad-hoc
  wireless-channel ${WLAN_CHANNEL}
  wireless-essid ${WLAN_SSID}
  wireless-key ${WLAN_KEY}
  address ${WLAN_IP}
  netmask ${WLAN_NM}
EOF
