#!/bin/sh

for tarname in $(find /tmp -maxdepth 1 -name "__*.tar"); do
    dname=$(basename -s .tar ${tarname} | sed 's/^__/\./')
    echo tar --strip-components 1 -Pxpf ${tarname} -C/home/${__object_id}/${dname}
    echo rm ${tarname}
done

