#!/bin/sh

uid=`cat "$__object/explorer/uid"`
gid=`cat "$__object/explorer/gid"`

for file in $(find ${__type}/files/ -maxdepth 1 -name '_*' -type f); do
    realname=$(basename ${file} | sed 's/^_/\./')
    __file /home/${__object_id}/${realname} --state present \
       --source ${file} \
       --owner ${uid} \
       --group ${gid}
done

mkdir -p $__object/files
for directory in $(find ${__type}/files/ -maxdepth 1 -name '_*' -type d); do
    tarname="__${__object_id}__$(basename ${directory} | sed 's/^_//').tar"
    dirname=${directory}/../
    tar -cf $__object/files/${tarname} \
        --owner ${uid} --group ${gid} \
        -C ${dirname} $(basename ${directory})
    __file /tmp/${tarname} --state present \
        --source $__object/files/${tarname}
done

__directory /home/${__object_id}/.vim --state present \
    --owner ${uid} \
    --group ${gid}

if [ -f "$__object/parameter/group" ]; then
    group=`cat "$__object/parameter/group"`
else
    group=$__object_id
fi

require="__directory/home/${__object_id}/.vim" \
    __git /home/${__object_id}/.vim/bundle/Vundle.vim \
        --source https://github.com/gmarik/Vundle.vim.git \
        --owner ${__object_id} \
        --group ${group}
