set nocompatible
" set backspace to be able to delete previous characters
set bs=2
" Enable line numbering, taking up 6 spaces
set number

"Turn off word wrapping
set wrap!
set textwidth=80

"Turn on smart indent
set expandtab
set autoindent
set tabstop=4 "set tab character to 4 characters
set softtabstop=4
set shiftwidth=4 "indent width for autoindent
filetype plugin indent on "indent depends on filetype

"Turn on incremental search with ignore case (except explicit caps)
set incsearch
set ignorecase
set smartcase

"Informative status line
set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\ [%l/%L\ (%p%%)]

"Set color scheme
set t_Co=256
colorscheme inkpot
syntax enable

set foldenable
"Set space to toggle a fold
nnoremap <space> za

highlight TrailingSpaces ctermbg=red
match TrailingSpaces / *$/

au BufNewFile,BufRead *.ino set filetype=cpp

au BufRead,BufNewFile *.go set makeprg=go\ build
