#!/bin/bash

packages="
wget
build-essential
"
for pkg in $packages
do
    __package $pkg --state present
done

tarfile="linuxcan.tar.gz"
version=$( cat $__object/parameter/version )
kvaser_url="http://www.kvaser.com/software/7330130980754/V${version}/${tarfile}"

