#!/bin/bash
# Every machine becomes a marker, so sysadmins know that automatic
# configurations are happening
__file /etc/cdist-configured

case "$__target_host" in
    blue18*)
        export WIRED_IP="192.168.180.20"
        export WLAN_IP="192.168.200.20"
        . $__manifest/samplereturn
        . $__manifest/samplereturn-laptop
        ;;
    moline*)
        export ETH0_IP="192.168.180.21"
        export WLAN_IP="192.168.200.21"
        . $__manifest/samplereturn
        . $__manifest/samplereturn-laptop
        ;;
    fordson*)
        export ETH0_IP="192.168.180.22"
        export WLAN_IP="192.168.200.22"
        . $__manifest/samplereturn
        . $__manifest/samplereturn-laptop
        ;;
    sr?)
        . $__manifest/samplereturn
        . $__manifest/samplereturn-robot
        ;;
    TheSmooth)
        . $__manifest/samplereturn
        ;;
    localhost)
        . $__manifest/samplereturn
        ;;
esac
