#!/bin/bash

packages="
git-all
terminator
tmux
gscanbus
coriander
nvidia-current-updates
htop
libgphoto2-2-dev
"

__package nvidia-experimental-310 --state absent
__package nvidia-settings-experimental-310 --state absent

for pkg in $packages
do
    __package $pkg --state present
done

# must manually create user first
# since dependency resolution does not work
__user robot \
       --home /home/robot \
       --shell /bin/bash

require="__user/robot" \
       __user_groups robot-groups \
       --user robot \
       --group dialout \
       --group cdrom \
       --group plugdev \
       --group lpadmin \
       --group sambashare \
       --group video \
       --group users

require="__user/robot" \
    __directory /home/robot \
    --owner robot \
    --group robot \
    --mode 755

require="__user/robot" \
    __ssh_authorized_keys \
    --key "$(cat $__manifest/files/robot_rsa.pub)" \
    robot
require="__ssh_authorized_keys/robot" \
    __file /home/robot/.ssh/robot_rsa \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa
require="__ssh_authorized_keys/robot" \
    __file /home/robot/.ssh/robot_rsa.pub \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa.pub

require="__user/robot" \
    __line autologin_user \
    --file /etc/lightdm/lightdm.conf \
    --line 'autologin-user=robot'
require="__user/robot" \
    __line autologin_timeout \
    --file /etc/lightdm/lightdm.conf \
    --line 'autologin-user-timeout=0'

require="__user/robot" \
    __directory /home/robot/.config \
    --owner robot \
    --group robot
require="__directory/home/robot/.config" \
    __directory /home/robot/.config/autostart \
    --owner robot \
    --group robot
require="__directory/home/robot/.config/autostart" \
    __file /home/robot/.config/autostart/roscore.desktop \
    --source $__manifest/files/roscore.desktop \
    --owner robot \
    --group robot \
    --mode 777

#require="__user/robot" \
#    __gsettings noautomount \
#    --user robot \
#    --schema org.gnome.desktop.media-handling \
#    --key automount \
#    --value false
require="__user/robot" \
    __dotfiles robot

require="__user/robot" \
    __git /home/robot/Desktop/SampleReturn \
        --source git://github.com/contradict/SampleReturn.git \
        --branch master \
        --owner robot \
        --group robot \
        --mode u+rwX,g+rwX,o+rX


__kvaser_canlib --tarname "linuxcan" --version "_BETA_20120702" --devices "leaf"

__package_apt libtbb-dev --state present
__package_apt libsuitesparse-dev --state present

__ros --distribution groovy
ros_extra_packages="
ros-groovy-camera-drivers
ros-groovy-joystick-drivers
ros-groovy-dynamixel-motor
ros-groovy-object-recognition-core
ros-groovy-object-recognition-capture
ros-groovy-object-recognition-linemod
ros-groovy-object-recognition-msgs
"
for ros_pkg in ${ros_extra_packages}; do
    require="__ros" __package_apt ${ros_pkg} --state present
done

__opencv --version=2.4.3

#__ros_opencv_overlay
#__line rossetup \
#    --line ". /opt/ros/opencv_overlay/overlay_setup.sh" \
#    --file "/etc/bash.bashrc"

if [ ${__target_host} = "sr2" ]; then
WIRED_ROUTES="  up route add -net 192.168.181.0 netmask 255.255.255.0 gw 192.168.180.31\
  down route del -net 192.168.181.0 netmask 255.255.255.0 gw 192.168.180.31\
"
fi
__samplereturn_network --WIRED_IP=$WIRED_IP --WIRELESS_IP=$WIRELESS_IP

__file /etc/udev/rules.d/80-hotplug-wlan.rules \
    --source $__manifest/files/80-hotplug-wlan.rules
