#!/bin/bash

require="__user/robot" \
    __line startuprobot \
        --file /etc/rc.local \
        --line ". /home/robot/Desktop/SampleReturn/src/scripts/rc.robot"

__samplereturn_network

crypted_pass='$6$IuyZIm6s$H4UMZipJV5HCLK6tSmSLExQTtnfx7ctLudBNGhzTLWcIeh/2.0z4xJGLECJfuc.34WIA3YBEhxOi.shfFYipR0'


require="__user/robot" \
    __directory /home/robot/sounds \
    --group robot \
    --mode 775 \
    --owner robot
hostname=$(cat $__global/explorer/hostname)
require="__directory/home/robot/sounds" \
    __file /home/robot/sounds/${hostname}start.wav \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/sounds/${hostname}start.wav
