#!/bin/bash

packages="
git-all
terminator
tmux
gscanbus
coriander
nvidia-current-updates
htop
libgphoto2-2-dev
"

__package nvidia-experimental-310 --state absent
__package nvidia-settings-experimental-310 --state absent

for pkg in $packages
do
    __package $pkg --state present
done

# must manually create user first
# since dependency resolution does not work
__user robot \
       --home /home/robot \
       --shell /bin/bash

require="__user/robot" \
       __user_groups robot-groups \
       --user robot \
       --group dialout \
       --group cdrom \
       --group plugdev \
       --group lpadmin \
       --group sambashare \
       --group video \
       --group users \
       --group sudo

require="__user/robot" \
    __directory /home/robot \
    --owner robot \
    --group robot \
    --mode 755

require="__user/robot" \
    __ssh_authorized_keys \
    --key "$(cat $__manifest/files/robot_rsa.pub)" \
    robot
require="__ssh_authorized_keys/robot" \
    __file /home/robot/.ssh/robot_rsa \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa
require="__ssh_authorized_keys/robot" \
    __file /home/robot/.ssh/robot_rsa.pub \
    --group robot \
    --mode 600 \
    --owner robot \
    --source $__manifest/files/robot_rsa.pub

require="__user/robot" \
    __dotfiles robot

require="__user/robot" \
    __git /home/robot/Desktop/SampleReturn \
        --source git://github.com/contradict/SampleReturn.git \
        --branch master \
        --owner robot \
        --group robot \
        --mode u+rwX,g+rwX,o+rX

__line robot_nofile_hard \
    --file /etc/security/limits.conf \
    --line "robot           hard    nofile          65535"
__line robot_nofile_soft \
    --file /etc/security/limits.conf \
    --line "robot           soft    nofile          65535"


__kvaser_canlib --tarname "linuxcan" --version "_BETA_20120702" --devices "leaf"

__package_apt libtbb-dev --state present
__package_apt libsuitesparse-dev --state present

__ros --distribution groovy
ros_extra_packages="
ros-groovy-camera-drivers
ros-groovy-joystick-drivers
ros-groovy-dynamixel-motor
ros-groovy-object-recognition-core
ros-groovy-object-recognition-capture
ros-groovy-object-recognition-linemod
ros-groovy-object-recognition-msgs
ros-groovy-navigation
ros-groovy-rqt-nav-view
"
for ros_pkg in ${ros_extra_packages}; do
    require="__ros" __package_apt ${ros_pkg} --state present
done

__opencv --version=2.4.3

